spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rds_mysql_z01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PRC&characterEncoding=UTF8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 2
mybatis-plus:
  global-config:
    banner: false
    db-config:
      update-strategy: not_null
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
logging:
  level:
    cn.zbq: debug
